# Universal Functions 

Arithmetic Functions 

In [21]:
import numpy as np

In [22]:
a=np.arange(1,31)
b=np.arange(31,61)
display(a,b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [23]:
#Addition
add_arr=np.add(a,b)
display(add_arr)

array([32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64,
       66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90])

In [24]:
#Subtraction
sub_arr=np.subtract(a,b)
display(sub_arr)

array([-30, -30, -30, -30, -30, -30, -30, -30, -30, -30, -30, -30, -30,
       -30, -30, -30, -30, -30, -30, -30, -30, -30, -30, -30, -30, -30,
       -30, -30, -30, -30])

In [25]:
#Multiply
multiply_arr=np.multiply(a,b)
display(multiply_arr)

array([  31,   64,   99,  136,  175,  216,  259,  304,  351,  400,  451,
        504,  559,  616,  675,  736,  799,  864,  931, 1000, 1071, 1144,
       1219, 1296, 1375, 1456, 1539, 1624, 1711, 1800])

In [26]:
#Divide
divide_arr=np.divide(a,b)
display(divide_arr)

array([0.03225806, 0.0625    , 0.09090909, 0.11764706, 0.14285714,
       0.16666667, 0.18918919, 0.21052632, 0.23076923, 0.25      ,
       0.26829268, 0.28571429, 0.30232558, 0.31818182, 0.33333333,
       0.34782609, 0.36170213, 0.375     , 0.3877551 , 0.4       ,
       0.41176471, 0.42307692, 0.43396226, 0.44444444, 0.45454545,
       0.46428571, 0.47368421, 0.48275862, 0.49152542, 0.5       ])

In [27]:
#Exponential
exp_arr=np.power(a,b)
display(exp_arr)

array([          1,           0, -1504003197,           0,  1165029885,
                 0,    12107431,           0,  -662744967,           0,
         865016235,           0,   142818741,           0, -1587542833,
                 0, -1863930895,           0,  1926776915,           0,
       -1950685843,           0,   189678711,           0,  1399551081,
                 0,  -745006725,           0,  2107894565,           0],
      dtype=int32)

In [29]:
#Remainder
remainder_arr=np.mod(a,b)
display(remainder_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], dtype=int32)

In [31]:
#Quotient and Remainder
quo_arr=np.divmod(a,b)
display(quo_arr)
#First array represents Quotients
#Second array represents Remainders

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], dtype=int32))

In [33]:
#Absolute(Removal of Signs)
abs_arr=np.absolute([-3,9,-2,-56,9])
display(abs_arr)

array([ 3,  9,  2, 56,  9])

Decimal Rounding

In [36]:
#Truncation OR Shortening 
short_arr =np.trunc([1.67,2.89,3.56,4.78,5.45,6.23,7.03,8.75,9.13,10.89])
display(short_arr)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [39]:
#rounding to n numbers
round_arr=np.around([8.907356,6.98222,4.0276,54.3242],2) #around(the numbers to round off, to which nth place to round)
display(round_arr)

array([ 8.91,  6.98,  4.03, 54.32])

In [40]:
#floor (round to lowest integer)
floor_arr=np.floor([7.98,-68.09,5.223,-45.23])
display(floor_arr)

array([  7., -69.,   5., -46.])

In [41]:
#ceil (round to highest integer)
ceil_arr=np.ceil([7.98,-68.09,5.223,-45.23])
display(ceil_arr)

array([  8., -68.,   6., -45.])

Summations

In [45]:
a=np.arange(1,31)
b=np.arange(31,61)
#Total sum of all elements
sum_arr=np.sum([a,b])
display(sum_arr) 

1830

In [47]:
#sum on an axis
sum_arr_ax1=np.sum([a,b],axis=1) #horizontal sum
display(sum_arr_ax1)

array([ 465, 1365])

In [50]:
#sum on an axis
sum_arr_ax0=np.sum([a,b],axis=0) #vertical sum
display(sum_arr_ax0)

array([32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64,
       66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90])

In [54]:
#cummulative sum
sum_cum=np.cumsum(np.arange(0,11))
display(sum_cum)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

Product

In [57]:
#product (multiplying all elements in an array)
prod_arr=np.product(a)
display(prod_arr)

1409286144

In [67]:
arr1=[1,2,3,4]
arr2=[5,6,7,8]
#product of two arrays
prod2_arr=np.product([arr1,arr2])
display(prod2_arr)

40320

In [73]:
#product over an axis
#axis=1
prod_arr_ax1=np.product([arr1,arr2],axis=1)
display("Axis=1", prod_arr_ax1)
#axis=0
prod_arr_ax0=np.product([arr1,arr2],axis=0)
display("Axis=0",prod_arr_ax0)

'Axis=1'

array([  24, 1680])

'Axis=0'

array([ 5, 12, 21, 32])

In [75]:
#cummulative product
cum_prod=np.cumprod(np.arange(1,11))
display(cum_prod)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

Logs

In [76]:
#log with base 2
arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
